### ISSUE TITLE
Room 32: possibly wrong description

### ISSUE THREAD

**Issue by graceman9** [deris/vim-duzzle#3]
First of all - thank you for the such cool game :-D

> Commands are allowed after the d in this room
> t: till before occurrence of {char} to the right

But there is no d command allowed!

> +--------+------------+--------+
> |s ((((( +------------+ ) ( ( (|
> +--------+------------+--------|
> +--------+
> +---)----+
> +--------+
> +--------+
> +---)----+
> +--------+            +--------+
> +---)----+            | )     g|
> +--------+            +--------+
> 
> [Room name]
> Room 32 
> 
> [Rule]
> Please move to exit (g).
> You will die if you move into the wall (+) or (-) or (|).
> 
> [Command that can be used in this room]
> h: move to left
> l: move to right
> %: find the next item in this line after or under the cursor and jump to its match
> 
> [Commands are allowed after the d in this room]
> t: till before occurrence of {char} to the right
> 
> [Count is not available]
> Count that can be specified before command is not available in this room
> Command execute [specified count] times
>

**Comment by deris** [comment]
Sorry for my late reply, and thank you for your issue.
I fixed it.
